
package com.pm.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JCServiceImpl", targetNamespace = "http://ws.pm.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JCServiceImpl {


    /**
     * 
     * @param fileId
     * @return
     *     returns com.pm.ws.CompileResponse
     */
    @WebMethod(action = "http://ws.pm.com/JCServiceImpl/compile")
    @WebResult(partName = "return")
    @Action(input = "http://ws.pm.com/JCServiceImpl/compile", output = "http://ws.pm.com/JCServiceImpl/compileResponse")
    public CompileResponse compile(
        @WebParam(name = "fileId", partName = "fileId")
        String fileId);

    /**
     * 
     * @param file
     * @return
     *     returns com.pm.ws.UploadResponse
     */
    @WebMethod(action = "http://ws.pm.com/JCServiceImpl/upload")
    @WebResult(partName = "return")
    @Action(input = "http://ws.pm.com/JCServiceImpl/upload", output = "http://ws.pm.com/JCServiceImpl/uploadResponse")
    public UploadResponse upload(
        @WebParam(name = "file", partName = "file")
        Upload file);

}
