
package com.pm.ws;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "JCServerImplService", targetNamespace = "http://ws.pm.com/")
public class JCServerImplService
    extends Service
{

	private static URL JCSERVERIMPLSERVICE_WSDL_LOCATION;
    private static WebServiceException JCSERVERIMPLSERVICE_EXCEPTION;
    private final static QName JCSERVERIMPLSERVICE_QNAME = new QName("http://ws.pm.com/", "JCServerImplService");

    public static void setWSDLLocAndException(URL url, WebServiceException ex){
    	JCSERVERIMPLSERVICE_WSDL_LOCATION = url;
    	JCSERVERIMPLSERVICE_EXCEPTION = ex;
    }
    
    public JCServerImplService() {
        super(__getWsdlLocation(), JCSERVERIMPLSERVICE_QNAME);
    }

    public JCServerImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), JCSERVERIMPLSERVICE_QNAME, features);
    }

    public JCServerImplService(URL wsdlLocation) {
        super(wsdlLocation, JCSERVERIMPLSERVICE_QNAME);
    }

    public JCServerImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, JCSERVERIMPLSERVICE_QNAME, features);
    }

    public JCServerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JCServerImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns JCServiceImpl
     */
    @WebEndpoint(name = "JCServerImplPort")
    public JCServiceImpl getJCServerImplPort() {
        return super.getPort(new QName("http://ws.pm.com/", "JCServerImplPort"), JCServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JCServiceImpl
     */
    @WebEndpoint(name = "JCServerImplPort")
    public JCServiceImpl getJCServerImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.pm.com/", "JCServerImplPort"), JCServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (JCSERVERIMPLSERVICE_EXCEPTION!= null) {
            throw JCSERVERIMPLSERVICE_EXCEPTION;
        }
        return JCSERVERIMPLSERVICE_WSDL_LOCATION;
    }

}
